HotelManagemant/Models/RegisterFood.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelManagemant.Models
{
    public class RegisterFood
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public string Ingredients { get; set; }
        public bool status { get; set; }
        public string ImageName { get; set; }
        [NotMapped]
        public HttpPostedFileBase Image { get; set; }
        public ICollection<FoodImage> FoodImages { get; set; }
        public FoodCategory FoodCategory { get; set; }
        public int FoodCategoryId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? EditedAt { get; set; }
        public string EditedBy { get; set; }

    }
}

HotelManagemant/Controllers/RegisterFoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using HotelManagemant.Data;
using HotelManagemant.Filters;
using HotelManagemant.Models;

namespace HotelManagemant.Controllers
{
    [SessionCheck]
    [Authorize(Roles = "Admin")]


    public class RegisterFoodsController : Controller
    {
        private Context db = new Context();

        // GET: RegisterFoods
        public ActionResult Index()
        {
            var registerFoods = db.RegisterFoods.Include(r => r.FoodCategory);
            return View(registerFoods.ToList());
        }

        // GET: RegisterFoods/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterFood registerFood = db.RegisterFoods.Include(a => a.FoodCategory).FirstOrDefault(a => a.Id == id);
                if (registerFood == null)
            {
                return HttpNotFound();
            }
            return View(registerFood);
        }

        // GET: RegisterFoods/Create
        public ActionResult Create()
        {
            ViewBag.FoodCategoryId = new SelectList(db.foodCategories, "Id", "CategoryName");
            return View();
        }

        // POST: RegisterFoods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        public List<FoodImage> fileDetails = new List<FoodImage>();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Quantity,Unit,Price,Ingredients,dicount,status,ImageName,FoodCategoryId")] RegisterFood registerFood, HttpPostedFileBase FImage, ICollection<HttpPostedFileBase> Image)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in Image)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        WebImage img = new WebImage(file.InputStream);
                        string firstpath = "/Images/";
                        string middlepath = "/Images/Food/";
                        string subPath = "/Images/Food/" + registerFood.Name + "/"; 
                        bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                        bool Mdexists = System.IO.Directory.Exists(Server.MapPath(middlepath));

                        bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                        if (!imageexist)
                        {
                            System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));
                        }
                        if (!Mdexists)
                        {
                            System.IO.Directory.CreateDirectory(Server.MapPath(middlepath));
                        }

                        if (!exists)
                        {
                            System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                        }
                       
                        string fileName1 = file.FileName;
                        string filename1 = Path.GetFileNameWithoutExtension(file.FileName);
                        string extension1 = Path.GetExtension(file.FileName);
                        filename1 = filename1 + extension1;
                        FoodImage image = new FoodImage()
                        {
                            ImageName = fileName1,
                            Path = Path.GetExtension(fileName1)

                        };
                        fileDetails.Add(image);

                        if (img.Width < 1000 || img.Width > 1000)
                            img.Resize(500, 500);
                        filename1 = Path.Combine(Server.MapPath("~/Images/Food/" + registerFood.Name + "/"), filename1);
                        img.Save(filename1);


                    }

                }
                int newid;
                try
                {

                    int getid = db.RegisterFoods.OrderByDescending(m => m.Id).FirstOrDefault().Id;
                     newid = getid + 1;

                }
                catch
                {
                     newid =  1;

                }

                registerFood.FoodImages = fileDetails;
                if (FImage != null)
                {
                    string fileName3 = FImage.FileName;
                    string firstpath = "/images/";
                    string subPath = "/images/Food/"; // your code goes here
                    bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                    bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                    if (!imageexist)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));
                    }
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                    }
                   
                    string filename3 = Path.GetFileNameWithoutExtension(FImage.FileName);
                    string extension3 = Path.GetExtension(FImage.FileName);
                    filename3 =newid + extension3;
                    registerFood.ImageName = "/images/Food/" + filename3;
                    filename3 = Path.Combine(Server.MapPath("~/images/Food/"), filename3);
                    FImage.SaveAs(filename3);
                }
                registerFood.CreatedAt = DateTime.Now;
                registerFood.CreatedBy = Session["userEmail"].ToString();
                db.RegisterFoods.Add(registerFood);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FoodCategoryId = new SelectList(db.foodCategories, "Id", "CategoryName", registerFood.FoodCategoryId);
            return View(registerFood);
        }

        // GET: RegisterFoods/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterFood registerFood = db.RegisterFoods.Find(id);
            if (registerFood == null)
            {
                return HttpNotFound();
            }
            ViewBag.FoodCategoryId = new SelectList(db.foodCategories, "Id", "CategoryName", registerFood.FoodCategoryId);
            return View(registerFood);
        }

        // POST: RegisterFoods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Quantity,Unit,Price,Ingredients,dicount,status,ImageName,FoodCategoryId")] RegisterFood registerFood, HttpPostedFileBase FImage )
        {
            if (ModelState.IsValid)
            {
                if (FImage != null)
                {
                    string fileName3 = FImage.FileName;
                    string firstpath = "/images/";
                    string subPath = "/images/Food/"; // your code goes here
                    bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                    bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                    if (!imageexist)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));
                    }
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                    }

                    string filename3 = Path.GetFileNameWithoutExtension(FImage.FileName);
                    string extension3 = Path.GetExtension(FImage.FileName);
                    filename3 = registerFood.Id + extension3;
                    registerFood.ImageName = "/images/Food/" + filename3;
                    filename3 = Path.Combine(Server.MapPath("~/images/Food/"), filename3);
                    FImage.SaveAs(filename3);
                }
                registerFood.EditedAt = DateTime.Now;
                registerFood.EditedBy = Session["userEmail"].ToString();

                db.Entry(registerFood).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FoodCategoryId = new SelectList(db.foodCategories, "Id", "CategoryName", registerFood.FoodCategoryId);
            return View(registerFood);
        }

        // GET: RegisterFoods/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterFood registerFood = db.RegisterFoods.Find(id);
            if (registerFood == null)
            {
                return HttpNotFound();
            }
            return View(registerFood);
        }

        // POST: RegisterFoods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RegisterFood registerFood = db.RegisterFoods.Find(id);
            db.RegisterFoods.Remove(registerFood);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {

HotelManagemant/Views/RegisterFoods/Create.cshtml
@model HotelManagemant.Models.RegisterFood

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


@using (Html.BeginForm("Create", "RegisterFoods", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="row">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">

            <label>Category Name</label>
            @Html.DropDownList("FoodCategoryId", null, "select Category", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FoodCategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">

            @Html.LabelFor(model => model.Quantity)
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="col-md-3">

        <div class="form-group">

            @Html.LabelFor(model => model.Unit)
            @Html.DropDownList("Unit", new List<SelectListItem> { new SelectListItem { Text = "---Select Unit--", Value = "" }, new SelectListItem { Text = "Meter", Value = "L" }, new SelectListItem { Text = "Liter", Value = "M" }, new SelectListItem { Text = "KiloGram", Value = "Kg" } }, new { @class = "form-control", id = "ddlCustomerType" })
            @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredients)
            @Html.EditorFor(model => model.Ingredients, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ingredients, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">

        <div class="col-md-3">

            @Html.LabelFor(model => model.status)
            <div class="checkbox checkbox-inline">
                @Html.EditorFor(model => model.status)
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label class="control-label col-md-2">Image</label>
            <input type="file" id="FImage" name="FImage" class="form-control" accept=".jpg , .png" />
            @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label class="control-label col-md-2">Images</label>

            <input type="file" id="Image" Name="Image" class="form-control" multiple />

        </div>
    </div>



    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Create" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })

        </div>
    </div>
</div>
}

HotelManagemant/Views/RegisterFoods/Delete.cshtml
@model HotelManagemant.Models.RegisterFood

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RegisterFood</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FoodCategory.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodCategory.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitQuintity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitQuintity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ingredients)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ingredients)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dicount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dicount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HotelManagemant/Views/RegisterFoods/Details.cshtml
@model HotelManagemant.Models.RegisterFood

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<style>
    table {
        border-collapse: collapse;
        witdh: 100%;
        border: 1px solid #ttd;
    }

    th, td {
        text-align: left;
        patding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>



<div class="panel-group">
    <div class="panel panel-primary">
        <div class="panel-heading">Details</div>

        <div class="panel-body">
            <table class="table table-responsive table-bordered">
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Name)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Name)
                    </td>

                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.FoodCategory.CategoryName)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.FoodCategory.CategoryName)
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Unit)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Unit)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Price)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Price)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Ingredients)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Ingredients)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.status)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.status)
                    </td>
                </tr>
            </table>
        </div>

        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id },new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-primary" })
        </p>
    </div>
</div>

HotelManagemant/Views/RegisterFoods/Edit.cshtml
@model HotelManagemant.Models.RegisterFood

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


@using (Html.BeginForm("Edit", "RegisterFoods", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="row">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">

            <label>Category Name</label>
            @Html.DropDownList("FoodCategoryId", null, "select Category", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FoodCategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">

            @Html.LabelFor(model => model.Quantity)
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="col-md-3">

        <div class="form-group">

            @Html.LabelFor(model => model.Unit)
            @Html.DropDownList("Unit", new List<SelectListItem> { new SelectListItem { Text = "---Select Unit--", Value = "" }, new SelectListItem { Text = "Meter", Value = "L" }, new SelectListItem { Text = "Liter", Value = "M" }, new SelectListItem { Text = "KiloGram", Value = "Kg" } }, new { @class = "form-control", id = "ddlCustomerType" })
            @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredients)
            @Html.EditorFor(model => model.Ingredients, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ingredients, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">

        <div class="col-md-3">

            @Html.LabelFor(model => model.status)
            <div class="checkbox checkbox-inline">
                @Html.EditorFor(model => model.status)
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label class="control-label col-md-2">Image</label>
            <input type="file" id="FImage" name="FImage" class="form-control" accept=".jpg , .png" />
            @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label class="control-label col-md-2">Images</label>

            <input type="file" id="Image" Name="Image" class="form-control" multiple />

        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Edit" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index",null,new { @class = "btn btn-primary" })

        </div>
    </div>
</div>
}

\

HotelManagemant/Views/RegisterFoods/Index.cshtml
@model IEnumerable<HotelManagemant.Models.RegisterFood>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<div class="panel-group">
    <div class="panel panel-primary">
        <div class="panel-heading"> Registered Food</div>

        <div class="panel-body">



            <table class="table tab-border table-responsive" id="table1">
                <thead>
                    <tr>

                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodCategory.CategoryName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Quantity)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Unit)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Ingredients)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.status)
                        </th>

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodCategory.CategoryName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Unit)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ingredients)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.status)
                        </td>

                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id })
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <p>
                @Html.ActionLink("Create New", "Create",null,new { @class = "btn btn-primary" })
            </p>
</div>
        </div>
    </div>

            <link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" />
            <link href="~/Content/DataTables/css/responsive.bootstrap.min.css" />
            <script src="~/Scripts/datatables/jquery.dataTables.min.js"></script>

            <script src="~/Scripts/datatables/dataTables.bootstrap4.min.js"></script>
            <script>
                $(function () {
                    $("#table1").DataTable();
                });
            </script>