HotelManagemant/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelManagemant.Models
{
    public class Room
    {
        public int id { get; set; }
        public Hotel Hotel { get; set; }
        public string RoomNo { get; set; }
        public int Capacity { get; set; }
        public int NoofBeds { get; set; }
        public string Roomtype { get; set; }
        public virtual ICollection<Facilities> Facilities { get; set; }
        public virtual  ICollection<Booking> Bookings { get; set; }
        public Decimal Price { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        [NotMapped]
        public HttpPostedFileBase Image { get; set; }

        public String Status { get; set; }
        public Room()
        {
            this.Facilities = new HashSet<Facilities>();
            this.Bookings = new HashSet<Booking>();
        }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? EditedAt { get; set; }
        public string EditedBy { get; set; }


    }

}

HotelManagemant/ViewModels/AddCustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelManagemant.ViewModels
{
    public class AddCustomerViewModel
    {
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string NationalIdNo { get; set; }
        public string BookingNo { get; set; }
        public string Nationality { get; set; }
    }
}

HotelManagemant/ViewModels/AddRoomViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HotelManagemant.Models;

namespace HotelManagemant.ViewModels
{
    public class AddRoomViewModel
    {
        public string BookingNo { get; set; }
        public int RoomId { get; set; }
        public IEnumerable<Room> rooms { get; set; }
    }
}

HotelManagemant/ViewModels/ChangeStatusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelManagemant.ViewModels
{
    public class ChangeStatusViewModel
    {
        public int RoomId { get; set; }
        public string RoomNo { get; set; }
        public string Status { get; set; }
        public List<String> RoomStatus { get; set; }
    }
}

HotelManagemant/ViewModels/bookViewModel.cs
using HotelManagemant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelManagemant.ViewModels
{
    public class bookViewModel
    {
        public int roomId { get; set; }
        public string bookingno { get; set; }
        public string roomNo { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckoutDate { get; set; }
        public string NoOfPersons { get; set; }
        public string ShortDescriptions { get; set; }
        public int Id { get; set; } 
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string NationalIdNo { get; set; }
        public string Nationality { get; set; }
        public decimal Price { get; set; }
        public int? Advanceprice { get; set; }

    }
}

HotelManagemant/ViewModels/printListViewModel.cs
using HotelManagemant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelManagemant.ViewModels
{
    public class printListViewModel
    {
        public string bookingno { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckoutDate { get; set; }
        public string ShortDescriptions { get; set; }
        public string noOfPerson { get; set; }
        public List<customers> customer { get; set; }
        public List<Room> Rooom { get; set; }
        public decimal AdvanceAmount { get; set; }
        public int BookingId { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal RemainAmount { get; set; }
        public int NoOfDays { get; set; }
        public string BillNo { get; set; }
    }
}

HotelManagemant/ViewModels/roomViewModel.cs
using HotelManagemant.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelManagemant.ViewModels
{
    public class roomViewModel
    {
        public string RoomNo { get; set; }
        public int Capacity { get; set; }
        public int NoofBeds { get; set; }
        public string Roomtype { get; set; }
        public virtual ICollection<int> facilitiesId { get; set; }
        public Decimal Price { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        [NotMapped]
        public HttpPostedFileBase Image { get; set; }

        public ICollection<Facilities> Facilities { get; set; }
        public String Status { get; set; }
    }
}

HotelManagemant/Controllers/RoomsController.cs
using System;
using System.Activities.Statements;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IdentityModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using HotelManagemant.Data;
using HotelManagemant.Models;
using HotelManagemant.ViewModels;
using System.Transactions;
using HotelManagemant.Filters;

namespace HotelManagemant.Controllers
{
    [SessionCheck]

    [Authorize(Roles ="Admin")]
    public class RoomsController : Controller
    {
        private Context db = new Context();

        // GET: Rooms
        public ActionResult Index()
        {
            return View(db.rooms.ToList());
        }

        // GET: Rooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // GET: Rooms/Create
        public ActionResult Create()
        {
            roomViewModel room = new roomViewModel();
            room.Facilities = db.facilities.ToList();
            return View(room);
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(roomViewModel room, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null)
                {
                    WebImage img = new WebImage(Image.InputStream);
                
                    string firstpath = "/Images/";
                    string subPath = "/Images/Rooms/"; // your code goes here
                    bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                    bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                    if (!imageexist)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));
                    }
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                    }
                   
                string fileName1 = Image.FileName;
                    string filename1 = Path.GetFileNameWithoutExtension(Image.FileName);
                    string extension1 = Path.GetExtension(Image.FileName);
                    filename1 = room.RoomNo + extension1;
                    room.ImageName = "/images/Rooms/" + filename1;
                    if (img.Width < 1000 || img.Width > 1000)
                        img.Resize(903, 631);
                    filename1 = Path.Combine(Server.MapPath("~/Images/Rooms/"), filename1);
                    img.Save(filename1);
                }
                var facilites = room.facilitiesId;
                ICollection<Facilities> objFacilities = new List<Facilities>();
                if (room.facilitiesId!=null)
                {
                    foreach (var item in facilites)
                    {
                        int id = Convert.ToInt32(item);
                        Facilities objfaci = db.facilities.Find(id);
                        objFacilities.Add(objfaci);
                    }
                }
                db.rooms.Add(new Room
                {
                    Facilities = objFacilities,
                    Capacity = room.Capacity,
                    Description = room.Description,
                    Image = room.Image,
                    ImageName = room.ImageName,
                    NoofBeds = room.NoofBeds,
                    Price = room.Price,
                    RoomNo = room.RoomNo,
                    Roomtype = room.Roomtype,
                    Status = "Available",
                   CreatedAt=DateTime.Now,
                CreatedBy = Session["userEmail"].ToString()

            });
                // db.rooms.Add(room);
                db.SaveChanges();

                TempData["Message"] = "Room Created Successfully.";

                return RedirectToAction("Index");
            }



            return View(room);
        }

        // GET: Rooms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,RoomNo,Capacity,NoofBeds,Roomtype,Price,Description,Status")] Room room, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {

                if (Image != null)
                {
                    WebImage img = new WebImage(Image.InputStream);

                    string firstpath = "/Images/";
                    string subPath = "/Images/Rooms/"; // your code goes here
                    bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                    bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                    if (!imageexist)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));
                    }
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                    }
                    string fileName1 =Image.FileName;
                    string filename1 = Path.GetFileNameWithoutExtension(Image.FileName);
                    string extension1 = Path.GetExtension(Image.FileName);
                    filename1 = room.RoomNo + extension1;
                  room.ImageName= "/images/Rooms/" + filename1;
                    if (img.Width < 1000 || img.Width > 1000)
                        img.Resize(903, 631);
                    filename1 = Path.Combine(Server.MapPath("~/Images/Rooms/"), filename1);
                    img.Save(filename1);
                }
                room.EditedAt = DateTime.Now;
                room.EditedBy = Session["userEmail"].ToString();

                db.Entry(room).State = EntityState.Modified;
                db.SaveChanges();

                TempData["Message"] = "Room Updated Successfully.";
                return RedirectToAction("Index");
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room room = db.rooms.Find(id);
            db.rooms.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        public ActionResult ChangeStatus(int id)
        {
            ChangeStatusViewModel objStatus = new ChangeStatusViewModel();
            objStatus.RoomStatus=new List<string> { "Maintenance", "Available" };
            Room objRoom = db.rooms.Find(id);
            objStatus.RoomId = objRoom.id;
            objStatus.RoomNo = objRoom.RoomNo;
            objStatus.Status = objRoom.Status;
            return View(objStatus);
        }

        [HttpPost]
        public ActionResult ChangeStatus(ChangeStatusViewModel changeStatus)
        {
            Room objRoom = db.rooms.Find(changeStatus.RoomId);
            objRoom.Status = changeStatus.Status;
            db.SaveChanges();   
            TempData["Message"] = "Status Changed Successfully.";
            return RedirectToAction("Book");
        }







        public ActionResult book()
        {

            return View(db.rooms.ToList());

        }

        public ActionResult bookRoom(List<int> id)
        {
            List<bookViewModel> objBook = new List<bookViewModel>();
            string bookingno = "";
            if (db.bookings.ToList().Count != 0)
            {
                bookingno = db.bookings.OrderByDescending(m => m.BookingId).FirstOrDefault().bookingNo;
            }

            if (bookingno == "" || bookingno == null)
            {
                bookingno = "Dbug2000";
            }
            else
            {
                var num = Regex.Matches(bookingno, @"\D+|\d+")
              .Cast<Match>()
              .Select(m => m.Value).ToList();
                int num1 = Convert.ToInt32(num[1]) + 1;
                bookingno = "DBUG" + num1;

            }
            foreach (int item in id)
            {
                Room objRoom = db.rooms.Find(item);
                bookViewModel objbookVM = new bookViewModel();
                objbookVM.roomId = item;
                objbookVM.roomNo = objRoom.RoomNo;
                objbookVM.bookingno = bookingno;
                objbookVM.Price = objRoom.Price;

HotelManagemant/Views/Rooms/AddCustomer.cshtml
@model HotelManagemant.ViewModels.AddCustomerViewModel
@{
    ViewBag.Title = "AddCustomer";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="fa fa-clock-o fa-fw"></i>Add Customer
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                @using (Html.BeginForm())
                {
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Booking No</label>
                            @Html.TextBoxFor(m => m.BookingNo, new { @class = "form-control", readOnly = "readOnly" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Name</label>
                            @Html.TextBoxFor(a => a.CustomerName, new { placeholder = "CustomerName", @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>NationalID No</label>
                            @Html.TextBoxFor(a => a.NationalIdNo, new { placeholder = "NationalIdNo", @class = "form-control" })
                        </div>

                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Address</label>
                            @Html.TextBoxFor(a => a.Address, new { placeholder = "Address", @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Nationality</label>
                            @Html.TextBoxFor(a => a.Nationality, new { placeholder = "Address", @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-12">
                        <input class="btn btn-primary" value="Add" type="submit" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

HotelManagemant/Views/Rooms/AddRoom.cshtml
@model HotelManagemant.ViewModels.AddRoomViewModel
@{
    /**/

    ViewBag.Title = "book";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="col-md-12">
<div class="bg-primary">
    <i class="fa fa-clock-o fa-fw"></i> Add Room
</div>  
    </div>

@foreach (var item in Model.rooms)
{

    string panelClass = "bg-success";
    if (item.Status == "Booked")
    {
        panelClass = "bg-danger";
    }
    <div style="padding-top:5px;" class="col-md-3 text-center">
        <div class="card" style="width:18rem; border-radius:25px;">
            @*<img class="card-img-top" src="~/Images/286_180.svg" alt="Card image cap" style="width:286px;height:180px;">*@

            <div class="card-body @panelClass">
                <p class="card-text">
                    RoomNo: @item.RoomNo<br />
                    Capacity: @item.Capacity<br />
                    No of Beds: @item.NoofBeds<br />
                    RoomType: @item.Roomtype<br />
                    Price: @item.Price<br />
                </p>
                <span class="text-center">
                    @*@Html.ActionLink("Book", "AddRoom", new { roomId = item.id,bookingNo=Model.BookingNo }, new { @class = "btn btn-default" })*@
                    @using (Html.BeginForm())
                    {
                        @Html.HiddenFor(m => m.BookingNo)
                        @Html.Hidden("RoomId", item.id)
                        if (panelClass == "bg-success")
                        {
                            <input type="submit" class="btn btn-default" value="Add" />
                        }
                        else
                        {
                            <input type="submit" class="btn btn-default" value="Add" disabled="disabled" />
                        }
                    }
                </span>
                <div style="height:5px;"></div>
            </div>
        </div>
    </div>

}
    }

HotelManagemant/Views/Rooms/BillIndex.cshtml
@model List<HotelManagemant.Models.Billing>

@{
    ViewBag.Title = "BillIndex";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="fa fa-clock-o fa-fw"></i>Saved Payments
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <table class="table table-bordered table-responsive">
                    <tr>
                        <th>Bill No </th>
                        <th>Booking No</th>
                        <th>No Of Days</th>
                        <th>Check Out Date</th>
                        <th>Print</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.BillNo</td>
                            <td>@item.Booking.bookingNo</td>
                            <td>@item.NoOfDays</td>
                            <td>@item.CheckOutDate.ToShortDateString()</td>
                            <td>@Html.ActionLink("BillPrint", "BillPrint", new { id = item.BillingId }, new { @class = "btn btn-default" })</td>

                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>

HotelManagemant/Views/Rooms/Create.cshtml
@model HotelManagemant.ViewModels.roomViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="fa fa-clock-o fa-fw"></i> Create Room
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                @using (Html.BeginForm("Create", "Rooms", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="col-md-12">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            @Html.LabelFor(model => model.RoomNo)
                            @Html.EditorFor(model => model.RoomNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RoomNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Capacity)
                            @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control", @minimumvalue = 1 } })
                            @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            @Html.LabelFor(model => model.NoofBeds)
                            @Html.EditorFor(model => model.NoofBeds, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NoofBeds, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Price)<span>(per night)</span>
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Roomtype)
                            @Html.EditorFor(model => model.Roomtype, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Roomtype, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="col-md-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <label>&nbsp;</label>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Facilities</label>

                            <div class="checkbox">
                                @foreach (var item in Model.Facilities)
                                {
                                    if (item.Type == "Room")
                                    {
                                        <label>  <input type="checkbox" name="facilitiesId" value="@item.Id" />@item.Name</label>

                                    }
                                }
                            </div>
                            @Html.ValidationMessageFor(model => model.facilitiesId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Image</label>
                            <input type="file" id="Image" name="Image" class="form-control" accept=".jpg , .png" />
                            @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <center>
                        <div class="col-md-12">
                            <input type="submit" value="Create" class="btn btn-primary" /> @Html.ActionLink("Back to List", "Index", "Rooms", null, new { @class = "btn btn-primary" })
                        </div>
                    </center>

                }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HotelManagemant/Views/Rooms/Edit.cshtml
@model HotelManagemant.Models.Room

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}



@using (Html.BeginForm("Edit", "Rooms", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <i class="fa fa-clock-o fa-fw"></i> Edit Room
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)
            <div class="form-group">
                @Html.LabelFor(model => model.RoomNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RoomNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RoomNo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Capacity, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NoofBeds, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoofBeds, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoofBeds, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Roomtype, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Roomtype, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Roomtype, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
           
            <div class="form-group">
                <label class="control-label col-md-2">Images</label>

                <div class="col-md-10">
                    <input type="file" id="Image" Name="Image" class="form-control" />

                </div>
            </div>
            
            
            @Html.HiddenFor(m => m.Status);

            <div class="form-group">
                <div class=" col-md-12">
                    <center>
                        <input type="submit" value="Edit" class="btn btn-primary" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                    </center>
                </div>
            </div>
        </div>
        </div>
    </div>
    
        }



        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }