HotelManagemant/Models/DrinkRegister.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelManagemant.Models
{
    public class DrinkRegister
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int  Quantity{ get; set; }
        public string UnitName { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public bool status { get; set; }
        public string ImageName { get; set; }
        [NotMapped]
        public HttpPostedFileBase Image { get; set; }
        public ICollection<DrinkImage> DrinkImage { get; set; }
        public DrinkCategory DrinkCategory { get; set; }
        public int DrinkCategoryId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? EditedAt { get; set; }
        public string EditedBy { get; set; }

    }
}

HotelManagemant/Controllers/DrinkRegistersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using HotelManagemant.Data;
using HotelManagemant.Filters;
using HotelManagemant.Models;

namespace HotelManagemant.Controllers
{
    [SessionCheck]
    [Authorize(Roles = "Admin")]

    public class DrinkRegistersController : Controller
    {
        private Context db = new Context();

        // GET: DrinkRegisters
        public ActionResult Index()
        {
            var drinkRegisters = db.drinkRegisters.Include(d => d.DrinkCategory);
            return View(drinkRegisters.ToList());
        }

        // GET: DrinkRegisters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrinkRegister drinkRegister = db.drinkRegisters.Include(b => b.DrinkCategory).FirstOrDefault(m => m.Id == id);
            if (drinkRegister == null)
            {
                return HttpNotFound();
            }
            return View(drinkRegister);
        }

        // GET: DrinkRegisters/Create
        public ActionResult Create()
        {
            ViewBag.DrinkCategoryId = new SelectList(db.drinkCategories, "Id", "CategoryName");
            return View();
        }
        public List<DrinkImage> fileDetails = new List<DrinkImage>();
        // POST: DrinkRegisters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DrinkRegister drinkRegister, HttpPostedFileBase FImage, ICollection<HttpPostedFileBase> Image)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in Image)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        WebImage img = new WebImage(file.InputStream);
                        string firstpath = "/Images/";
                        string middlepath = "/Images/Drink/";
                        string subPath = "/Images/Drink/" + drinkRegister.Name + "/";
                        bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                        bool Mdexists = System.IO.Directory.Exists(Server.MapPath(middlepath));

                        bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                        if (!imageexist)
                        {
                            System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));

                        }
                        if (!Mdexists)
                        {
                            System.IO.Directory.CreateDirectory(Server.MapPath(middlepath));
                        }

                        if (!exists)
                        {
                            System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                        }

                        string fileName1 = file.FileName;
                        string filename1 = Path.GetFileNameWithoutExtension(file.FileName);
                        string extension1 = Path.GetExtension(file.FileName);
                        filename1 = filename1 + extension1;
                        DrinkImage image = new DrinkImage()
                        {
                            ImageName = fileName1,
                            Path = Path.GetExtension(fileName1)

                        };
                        fileDetails.Add(image);

                        if (img.Width < 1000 || img.Width > 1000)
                            img.Resize(500, 500);
                        filename1 = Path.Combine(Server.MapPath("~/Images/Drink/" + drinkRegister.Name + "/"), filename1);
                        img.Save(filename1);


                    }

                }
                int newid;
                try
                {
                    int getid = db.drinkRegisters.OrderByDescending(m => m.Id).FirstOrDefault().Id;
                    //int id = getid.Id;tch
                    
                     newid = getid + 1;
                }
                catch
                {
                    newid = 1;
                }
                if (FImage != null)
                {
                    string fileName3 = FImage.FileName;
                    string firstpath = "/images/";
                    string subPath = "/images/Drink/"; // your code goes here
                    bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                    bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                    if (!imageexist)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));
                    }
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                    }

                    string filename3 = Path.GetFileNameWithoutExtension(FImage.FileName);
                    string extension3 = Path.GetExtension(FImage.FileName);
                    filename3 = newid + extension3;
                    drinkRegister.ImageName = "/images/Drink/" + filename3;
                    filename3 = Path.Combine(Server.MapPath("~/images/Drink/"), filename3);
                    FImage.SaveAs(filename3);
                }
                drinkRegister.CreatedAt = DateTime.Now;
                drinkRegister.CreatedBy = Session["userEmail"].ToString();

                db.drinkRegisters.Add(drinkRegister);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                
            }
            ViewBag.DrinkCategoryId = new SelectList(db.drinkCategories, "Id", "CategoryName", drinkRegister.DrinkCategoryId);
            return View(drinkRegister);
        }

        // GET: DrinkRegisters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrinkRegister drinkRegister = db.drinkRegisters.Find(id);
            if (drinkRegister == null)
            {
                return HttpNotFound();
            }
            ViewBag.DrinkCategoryId = new SelectList(db.drinkCategories, "Id", "Id", drinkRegister.DrinkCategoryId);

            return View(drinkRegister);
        }

        // POST: DrinkRegisters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,UnitQuantity,UnitName,UnitPrice,Description,dicount,status,DrinkCategoryId")] DrinkRegister drinkRegister, HttpPostedFileBase FImage)
        {
            if (ModelState.IsValid)
            {
                if (FImage != null)
                {
                    string fileName3 = FImage.FileName;
                    string firstpath = "/images/";
                    string subPath = "/images/Drink/"; // your code goes here
                    bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                    bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                    if (!imageexist)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));
                    }
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                    }

                    string filename3 = Path.GetFileNameWithoutExtension(FImage.FileName);
                    string extension3 = Path.GetExtension(FImage.FileName);
                    filename3 = drinkRegister.Id + extension3;
                    drinkRegister.ImageName = "/images/Drink/" + filename3;
                    filename3 = Path.Combine(Server.MapPath("~/images/Drink/"), filename3);
                    FImage.SaveAs(filename3);
                }
                drinkRegister.EditedAt = DateTime.Now;
                drinkRegister.EditedBy = Session["userEmail"].ToString();

                db.Entry(drinkRegister).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DrinkCategoryId = new SelectList(db.drinkCategories, "Id", "Id", drinkRegister.DrinkCategoryId);
            return View(drinkRegister);
        }

        // GET: DrinkRegisters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrinkRegister drinkRegister = db.drinkRegisters.Find(id);
            if (drinkRegister == null)
            {
                return HttpNotFound();
            }
            return View(drinkRegister);
        }

        // POST: DrinkRegisters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DrinkRegister drinkRegister = db.drinkRegisters.Find(id);
            db.drinkRegisters.Remove(drinkRegister);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

HotelManagemant/Views/DrinkRegisters/Create.cshtml
@model HotelManagemant.Models.DrinkRegister

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}



@using (Html.BeginForm("Create", "DrinkRegisters", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="row">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label>Category Name</label>
            @Html.DropDownList("DrinkCategoryId", null, "select Category", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DrinkCategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity)
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-3">

        <div class="form-group">
<label>Unit Name</label>
            @Html.EditorFor(model => model.UnitName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Description)
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.status)
            <div class="checkbox checkbox-inline" >
                @Html.EditorFor(model => model.status)
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label>Image</label>
            <input type="file" id="FImage" name="FImage" class="form-control" accept=".jpg , .png" />
            @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label>Images</label>

            <input type="file" id="Image" name="Image" class="form-control" multiple />

        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", null,new { @class = "btn btn-primary" })

        </div>
    </div>
</div>
    }

    

HotelManagemant/Views/DrinkRegisters/Delete.cshtml
@model HotelManagemant.Models.DrinkRegister

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DrinkRegister</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DrinkCategory.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DrinkCategory.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HotelManagemant/Views/DrinkRegisters/Details.cshtml
@model HotelManagemant.Models.DrinkRegister

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<style>
    table {
        border-collapse: collapse;
        witdh: 100%;
        border: 1px solid #ttd;
    }

    th, td {
        text-align: left;
        patding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>



<div class="panel-group">
    <div class="panel panel-primary">
        <div class="panel-heading">Details</div>

        <div class="panel-body">
            <table class="table table-responsive table-bordered">
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Name)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DrinkCategory.CategoryName)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.DrinkCategory.CategoryName)
                    </td>
                </tr>



                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.UnitName)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.UnitName)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Price)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Price)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Description)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Description)
                    </td>
                </tr>
                <tr>

                    <td>
                        @Html.DisplayNameFor(model => model.status)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.status)
                    </td>
                </tr>
            </table>
        </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" }) |
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
    </p>
</div>
    </div>

HotelManagemant/Views/DrinkRegisters/Edit.cshtml
@model HotelManagemant.Models.DrinkRegister

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


@using (Html.BeginForm("Edit", "DrinkRegisters", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="row">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label>Category Name</label>
            @Html.DropDownList("DrinkCategoryId", null, "select Category", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DrinkCategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity)
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="col-md-3">

        <div class="form-group">
            <label>Unit Name</label>
            @Html.EditorFor(model => model.UnitName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.Description)
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="col-md-3">

        <div class="form-group">
            @Html.LabelFor(model => model.status)
            <div class="checkbox checkbox-inline">
                @Html.EditorFor(model => model.status)
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label>Image</label>
            <input type="file" id="FImage" name="FImage" class="form-control" accept=".jpg , .png" />
            @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-3">

        <div class="form-group">
            <label>Images</label>

            <input type="file" id="Image" name="Image" class="form-control" multiple />

        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Edit" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index",null,new { @class = "btn btn-primary" })

        </div>
    </div>
</div>
}

HotelManagemant/Views/DrinkRegisters/Index.cshtml
@model IEnumerable<HotelManagemant.Models.DrinkRegister>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="panel-group">
    <div class="panel panel-primary">
        <div class="panel-heading">Drinks</div>

        <div class="panel-body">

            <table class="table table-bordered table-responsive" id="table1">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.DrinkCategory.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.UnitName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.status)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.DrinkCategory.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.UnitName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.status)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id })
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
            
            <p>
                @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
            </p>
            </div>
        </div>
    </div>

            <link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" />
            <link href="~/Content/DataTables/css/responsive.bootstrap.min.css" />
            <script src="~/Scripts/datatables/jquery.dataTables.min.js"></script>

            <script src="~/Scripts/datatables/dataTables.bootstrap4.min.js"></script>
            <script>


                $(function () {
                    $("#table1").DataTable();
                });
            </script>