HotelManagemant/Models/MenuCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelManagemant.Models
{
    public class MenuCategory
    {
        public int id { get; set; }
        public String CategoryName { get; set;  }
        public string Detail { get; set; }
        public string thumbnail { get; set; }
        [NotMapped]
        public HttpPostedFileBase Image { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? EditedAt { get; set; }
        public string EditedBy { get; set; }

    }
}

HotelManagemant/Controllers/MenuCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HotelManagemant.Data;
using HotelManagemant.Filters;
using HotelManagemant.Models;

namespace HotelManagemant.Controllers
{
    [Authorize(Roles = "Admin")]
    [SessionCheck]


    public class MenuCategoriesController : Controller
    {
        private Context db = new Context();

        // GET: MenuCategories
        public ActionResult Index()
        {
            return View(db.Menu.ToList());
        }

        // GET: MenuCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuCategory menuCategory = db.Menu.Find(id);
            if (menuCategory == null)
            {
                return HttpNotFound();
            }
            return View(menuCategory);
        }

        // GET: MenuCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MenuCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,CategoryName,Detail")] MenuCategory menuCategory,HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null)
                {
                    string fileName3 = Image.FileName;
                    string firstpath = "/images/";
                    string subPath = "/images/Thumbail/"; // your code goes here
                    bool imageexist = System.IO.Directory.Exists(Server.MapPath(firstpath));
                    bool exists = System.IO.Directory.Exists(Server.MapPath(subPath));
                    if (!imageexist)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(firstpath));
                    }
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(subPath));
                    }
                   
                    string filename3 = Path.GetFileNameWithoutExtension(Image.FileName);
                    string extension3 = Path.GetExtension(Image.FileName);
                    filename3 = menuCategory.CategoryName + extension3;
                    menuCategory.thumbnail = "/images/Thumbail/" + filename3;
                    filename3 = Path.Combine(Server.MapPath("~/images/Thumbail/"), filename3);
                    Image.SaveAs(filename3);


                }

                db.Menu.Add(menuCategory);
                db.SaveChanges();
                TempData["Message"] = "Category Created Successfully.";

                return RedirectToAction("Index");
            }

            return View(menuCategory);
        }

        // GET: MenuCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuCategory menuCategory = db.Menu.Find(id);
            if (menuCategory == null)
            {
                return HttpNotFound();
            }
            return View(menuCategory);
        }

        // POST: MenuCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,CategoryName,Detail,thumbnail,Image")] MenuCategory menuCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menuCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menuCategory);
        }

        // GET: MenuCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MenuCategory menuCategory = db.Menu.Find(id);
            if (menuCategory == null)
            {
                return HttpNotFound();
            }
            return View(menuCategory);
        }

        // POST: MenuCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MenuCategory menuCategory = db.Menu.Find(id);
            db.Menu.Remove(menuCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HotelManagemant/Views/MenuCategories/Create.cshtml
@model HotelManagemant.Models.MenuCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","MenuCategories", FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Image" class="form-control" />
                @Html.ValidationMessageFor(model => model.thumbnail, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-12">
                <center>
                    <input type="submit" value="Create" class="btn btn-primary" />
                </center>
            </div>
        </div>
    </div>
}

<div>
    <center>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
        </center>
</div>

HotelManagemant/Views/MenuCategories/Delete.cshtml
@model HotelManagemant.Models.MenuCategory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MenuCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.thumbnail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thumbnail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HotelManagemant/Views/MenuCategories/Details.cshtml
@model HotelManagemant.Models.MenuCategory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<style>
    table {
        border-collapse: collapse;
        width: 100%;
        border: 1px solid #ddd;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<div>
    <div style="overflow-x:auto;">
        <div class="alert">
            <table class="table table-responsive table-bordered">

                <tr>
                        <td>
                            @Html.DisplayNameFor(model => model.CategoryName)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.CategoryName)
                        </td>
                    </tr>
                <tr>
                    <td>
                            @Html.DisplayNameFor(model => model.Detail)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.Detail)
                        </td>
                    </tr>
                <tr>
                        <td>
                            @Html.DisplayNameFor(model => model.thumbnail)
                        </td>

                        <td>
                            <img src="@Model.thumbnail" />
                        </td>

                      

                    </tr>
                </div>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.id },new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Back to List", "Index",null,new { @class = "btn btn-primary" })
                </p>

HotelManagemant/Views/MenuCategories/Edit.cshtml
@model HotelManagemant.Models.MenuCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.thumbnail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.thumbnail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HotelManagemant/Views/MenuCategories/Index.cshtml
@model IEnumerable<HotelManagemant.Models.MenuCategory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}




<p>
    @Html.ActionLink("Create New", "Create",null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Detail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.thumbnail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Detail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.thumbnail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }, new { @class = "btn btn-primary" }) |
            </td>
        </tr>
    }

</table>